name: .NET Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --sc false -r win-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true
    - name: Upload build artifact (executable)
      uses: actions/upload-artifact@v3.1.0
      with:
        name: xivsniff-win-x64.exe
        path: ./XIVSniff/bin/Release/win-x64/publish/xivsniff.exe
    - name: Upload build artifact (pdb)
      uses: actions/upload-artifact@v3.1.0
      with:
        name: xivsniff-win-x64.pdb
        path: ./XIVSniff/bin/Release/win-x64/publish/xivsniff.pdb
